//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by emule.rc
//
#define IDC_STATUSBAR                   100
#define IDD_EMULE_DIALOG                102
#define IDD_SMTPSERVER                  103
#define IDD_TRANSFER                    134
#define IDD_SERVER                      136
#define IDD_FILES                       140
#define IDD_SEARCH                      142
#define IDD_HTTPDOWNLOAD                163
#define IDD_CHAT                        165
#define IDR_HTTPDOWNLOAD_ANI            168
#define IDD_SOURCEDETAILWND             175
#define IDB_UP                          278
#define IDB_DOWN                        281
#define IDD_PPG_CONNECTION              309
#define IDD_PPG_DIRECTORIES             311
#define IDD_PPG_FILES                   313
#define IDD_PPG_GENERAL                 315
#define IDD_PPG_SERVER                  317
#define IDC_SMTPAUTH_LBL                368
#define IDB_UP2X                        601
#define IDB_DOWN2X                      603
#define IDD_PPG_STATS                   623
#define IDD_FILEINFO                    713
#define IDD_COMMENT                     751
#define IDD_COMMENTLST                  753
#define IDD_MULETRAYDLG                 776
#define IDC_CHECK4UPDATE                842
#define IDD_LISTVIEW_SEARCH             872
#define IDD_INPUTBOX                    933
#define IDD_PPG_SCHEDULER               974
#define IDC_SPEED                       1002
#define IDC_TOMAX                       1003
#define IDC_RESTORE                     1004
#define IDC_TOMIN                       1005
#define IDC_CONNECT                     1006
#define IDC_DISCONNECT                  1007
#define IDC_DOWNSLD                     1009
#define IDC_DOWNTXT                     1010
#define IDC_UPSLD                       1011
#define IDC_UPTXT                       1012
#define IDC_SIDEBAR                     1013
#define IDC_TRAYDOWN                    1014
#define IDC_TRAYUP                      1015
#define IDD_META_DATA                   1170
#define IDC_BTN_THIRDPARTY              2401
#define IDD_DIRECT_DOWNLOAD             1347
#define IDD_SEARCH_PARAMS               1348
#define IDD_NETWORK_INFO                1361
#define IDR_WIDECHARLOWERMAP            1362
#define IDD_ADDSOURCE                   1365
#define IDD_MINIMULE                    1412
#define IDR_HTML_MINIMULE               1481
#define IDR_LISTVIEW                    1481
#define IDD_DOWNLOAD_TOOLBARS           1564
#define IDD_FILESTATISTICS              1565
#define IDC_ANIMATE1                    2000
#define IDC_STATUS                      2001
#define IDC_FILESTATUS                  2002
#define IDC_TIMELEFT                    2003
#define IDC_TRANSFER_RATE               2004
#define IDC_MAXSOURCEPERFILE            2005
#define IDC_TITLEWINDOW                 2006
#define IDC_INPUTWINDOW                 2007
#define IDC_IRC_SERVER_BOX              2008
#define IDC_ELINK                       2010
#define IDC_IRC_NAME_BOX                2011
#define IDC_NICK                        2012
#define IDC_LOGBOX                      2013
#define IDC_IRC_NICK_BOX                2016
#define IDC_WIZ_TRUEDOWNLOAD_BOX        2018
#define IDC_VIDEOPLAYER                 2020
#define IDC_VIDEOPLAYER_ARGS            2021
#define IDC_MAXCON                      2023
#define IDC_QUEUE_REFRESH_BUTTON        2026
#define IDC_BROWSEV                     2027
#define IDC_REMOVE                      2028
#define IDC_TMPLBROWSE                  2029
#define IDC_SELECT_HYPERTEXT_FONT       2030
#define IDC_RESETHIST                   2031
#define IDC_ADDITEM                     2032
#define IDC_INCFILES                    2035
#define IDC_UPLOADLIST                  2036
#define IDC_NICKLIST                    2037
#define IDC_IRC_PERFORM_BOX             2038
#define IDC_MYINFOLIST                  2041
#define IDC_TAGS                        2042
#define IDC_CONTACTLIST                 2043
#define IDC_RETRY                       2045
#define IDC_FRIENDS_LIST                2047
#define IDC_DOWNLOADLIST                2048
#define IDC_RELOADSHAREDFILES           2049
#define IDC_RELOADSHAREDFILES2          2050
#define IDC_UPDATE_METADATA             2050
#define IDC_TOOLTIPDELAY                2052
#define IDC_CLEARALL                    2053
#define IDC_SELINCDIR                   2054
#define IDC_TAKEOVER                    2055
#define IDC_ADD                         2058
#define IDC_COLOR_BUTTON                2059
#define IDC_EDITADR                     2060
#define IDC_BROWSE                      2061
#define IDC_RELOADFILTER                2062
#define IDC_REB                         2062
#define IDC_HOTMENU                     2063
#define IDC_LOADURL                     2063
#define IDC_WSRELOADTMPL                2064
#define IDC_BOOTSTRAPBUTTON             2065
#define IDC_PV_EXIT                     2066
#define IDC_DEBUG_OPTS                  2067
#define IDC_TRAFFIC_TEXT                2069
#define IDC_CLOSECHAT                   2071
#define IDD_GEOLITE_DOWNLOAD            1690
#define IDD_MIGRATION_WIZARD            1691
#define IDC_GEOLITECITY_TEXT            3046
#define IDC_GEOLITECITY_DOWNLOAD        3047
#define IDC_MIGRATION_MESSAGE           3048
#define IDC_MIGRATION_SOURCE_DIR        3049
#define IDC_MIGRATION_SOURCE_DIR_LABEL  3050
#define IDC_MIGRATION_SELECT_DIR        3051
#define IDC_MIGRATION_DETAILS           3052
#define IDC_LANGUAGE_ICON               3053
#define IDC_MIGRATION_ICON              3054
#define IDC_LANGUAGE_PROMPT             3055
#define IDC_WIZ1_EXTRES_TEXT            3057
#define IDC_SEARCH_RESET                2076
#define IDC_PV_NEXT                     2078
#define IDC_CONVREMOVE                  2080
#define IDC_PV_PRIOR                    2084
#define IDC_SERVLIST_TEXT               2085
#define IDC_SERVLIST                    2091
#define IDC_CANCELS                     2093
#define IDC_STATTREE                    2094
#define IDC_EXT_OPTS                    2095
#define IDC_IPADDRESSPORT                   2098
#define IDC_SDOWNLOAD                   2099
#define IDC_SERVERRETRIES               2105
#define IDC_IRC_MINUSER_BOX             2108
#define IDC_SHOWCATINFO                 2110
#define IDC_ADVSPAMFILTER               2112
#define IDC_CB_TBN_ONNEWDOWNLOAD        2113
#define IDC_MSHOWSMILEYS                2113
#define IDC_NETWORK_KADEMLIA            2114
#define IDC_USECAPTCHAS                 2114
#define IDC_WIZARD_NETWORK_ED2K         2115
#define IDC_SERVERMETURL                2118
#define IDC_WIZ_XP_RADIO                2122
#define IDC_SHOWRATEONTITLE             2123
#define IDC_WSENABLEDLOW                2125
#define IDC_S_ENABLE                    2126
#define IDC_SCORE                       2128
#define IDC_IRC_USEPERFORM              2130
#define IDC_FULLCHUNKTRANS              2131
#define IDC_SHOWOVERHEAD                2132
#define IDC_INDICATERATINGS             2133
#define IDC_USESECIDENT                 2134
#define IDC_RUNASUSER                   2135
#define IDC_MMENABLED                   2136
#define IDC_ENABLEOBFUSCATION           2136
#define IDC_ONLYOBFUSCATED              2137
#define IDC_WIZ_ME_RADIO                2139
#define IDC_DISABLEOBFUSCATION          2139
#define IDC_SHOWDWLPERCENT              2140
#define IDC_SEARCHSPAMFILTER            2140
#define IDC_TEMPFILES                   2144
#define IDC_WIZ_APPLY_BUTTON            2149
#define IDC_WIZ_CANCEL_BUTTON           2153
#define IDC_PORT                        2162
#define IDC_APPLY                       2164
#define IDC_UPLOAD_CAP                  2166
#define IDC_SFLIST                      2167
#define IDC_ADDSERVER                   2169
#define IDC_DOWNLOAD_CAP                2171
#define IDC_SEARCHLIST                  2172
#define IDC_KADSEARCHLIST               2173
#define IDC_UPDATESERVERMETFROMURL      2174
#define IDC_COMBO1                      2175
#define IDC_AUTOSERVER                  2176
#define IDC_LENGTH                      2178
#define IDC_ED2KCONNECT                 2179
#define IDC_PROGRESS1                   2180
#define IDC_MINTRAY                     2181
#define IDC_VCODEC                      2182
#define IDC_SEARCHNAME                  2183
#define IDC_AUTOCONNECT                 2185
#define IDC_VBITRATE                    2186
#define IDC_CONV_PB_CURRENT             2187
#define IDC_CLEARCOMPL                  2188
#define IDC_STARTS                      2189
#define IDC_SHOWTRANSTOOLBAR            2189
#define IDC_UPDATESERVERCONNECT         2190
#define IDC_STORESEARCHES               2190
#define IDC_VWIDTH                      2191
#define IDC_WIN7TASKBARGOODIES          2191
#define IDC_QUEUECOUNT                  2192
#define IDC_VASPECT                     2192
#define IDC_UPDATESERVERCLIENT          2194
#define IDC_MORE                        2196
#define IDC_FLAT                        2197
#define IDC_VFPS                        2198
#define IDC_ACODEC                      2199
#define IDC_ABITRATE                    2200
#define IDC_CSEND                       2201
#define IDC_ACHANNEL                    2202
#define IDC_ASAMPLERATE                 2203
#define IDC_CCLOSE                      2204
#define IDC_CHATSEL                     2205
#define IDC_CMESSAGE                    2206
#define IDC_TEXT_FORMAT                 2207
#define IDC_SSTATIC                     2208
#define IDC_SSTATIC3                    2209
#define IDC_SSTATIC4                    2210
#define IDC_SSTATIC5                    2211
#define IDC_QUEUECOUNT_LABEL            2212
#define IDC_SSTATIC6                    2213
#define IDC_CURSESSION_LBL              2216
#define IDC_FSTATIC2                    2217
#define IDC_MYINFO                      2219
#define IDC_MSTATIC3                    2221
#define IDC_FSTATIC4                    2222
#define IDC_FSTATIC5                    2223
#define IDC_FSTATIC6                    2225
#define IDC_FRIENDS_LBL                 2226
#define IDC_DNAME                       2227
#define IDC_FSTATIC7                    2228
#define IDC_DSOFT                       2229
#define IDC_SREQUESTED                  2230
#define IDC_SACCEPTED                   2234
#define IDC_DSIP                        2235
#define IDC_STRANSFERRED                2236
#define IDC_DHASH                       2237
#define IDC_FSTATIC8                    2238
#define IDC_FSTATIC9                    2240
#define IDC_DID                         2241
#define IDC_SREQUESTED2                 2242
#define IDC_DSNAME                      2243
#define IDC_SACCEPTED2                  2244
#define IDC_DDOWNLOADING                2245
#define IDC_STRANSFERRED2               2246
#define IDC_DDOWN                       2247
#define IDC_DAVDR                       2248
#define IDC_DDUP                        2249
#define IDC_DAVUR                       2250
#define IDC_DDOWNTOTAL                  2251
#define IDC_DUPTOTAL                    2252
#define IDC_DRATIO                      2253
#define IDC_UPLOADING                   2254
#define IDC_DRATING                     2255
#define IDC_DSCORE                      2256
#define IDC_FD_XI1                      2259
#define IDC_FD_XI2                      2261
#define IDC_POPBAR                      2262
#define IDC_POPBAR4                     2263
#define IDC_FD_XI5                      2264
#define IDC_POPBAR2                     2265
#define IDC_SHARESELECTOR               2266
#define IDC_POPBAR5                     2266
#define IDC_FD_XI7                      2267
#define IDC_POPBAR3                     2268
#define IDC_POPBAR6                     2269
#define IDC_SCOPE_D                     2270
#define IDC_FD_XI9                      2271
#define IDC_FD_XI14                     2272
#define IDC_SLIDER                      2276
#define IDC_FD_XI13                     2277
#define IDC_FD_XI6                      2280
#define IDC_FD_XI8                      2282
#define IDC_FD_XI10                     2284
#define IDC_FD_XI12                     2286
#define IDC_STATISTICS                  2289
#define IDC_STATSSCOPE                  2291
#define IDD_STATISTICS                  2296
#define IDD_SPLASH                      2300
#define IDD_IRC                         2303
#define IDD_LANGUAGE_SELECT             2304
#define IDC_SCOPE_U                     2305
#define IDC_BEEPER                      2308
#define IDC_EXIT                        2311
#define IDC_SPLASHON                    2315
#define IDC_TYPESEARCH                  2322
#define IDC_FILTER                      2327
#define IDC_IRC_USECHANFILTER           2329
#define IDC_UDPDISABLE                  2330
#define IDC_PREVIEWPRIO                 2332
#define IDC_DISABLEKNOWNLIST            2333
#define IDC_WIZARD_NETWORK_KADEMLIA     2334
#define IDC_FNAME                       2335
#define IDC_COMMENTFILTER               2336
#define IDC_METFILE                     2337
#define IDC_ADDNEWFILESPAUSED           2338
#define IDC_FHASH                       2339
#define IDC_FSIZE                       2340
#define IDC_SAFESERVERCONNECT           2341
#define IDC_FD_AICHHASH                 2341
#define IDC_PFSTATUS                    2343
#define IDC_PARTCOUNT                   2344
#define IDC_TRANSFERRED                 2345
#define IDC_COMPLSIZE                   2346
#define IDC_DATARATE                    2348
#define IDC_SOURCECOUNT                 2349
#define IDC_SPLITTER                    2351
#define IDC_DBLCLICK                    2354
#define IDC_DBLCLICKFILENAMEPREVIEW     2401
#define IDC_LASTSEENCOMPL               2355
#define IDC_STARTMIN                    2356
#define IDC_FILECREATED                 2357
#define IDC_LASTRECEIVED                2358
#define IDC_LANGS                       2359
#define IDC_DL_ACTIVE_TIME              2359
#define IDC_SEESHARE1                   2360
#define IDC_SEESHARE2                   2361
#define IDC_SEESHARE3                   2362
#define IDC_NETWORK_ED2K                2363
#define IDC_BRINGTOFOREGROUND           2365
#define IDC_AUTOCONNECTSTATICONLY       2367
#define IDC_STARTNEXTFILE               2368
#define IDC_DISABLEQUEUELIST            2369
#define IDC_REMEMBERDOWNLOADED          2369
#define IDC_REMOVEDEAD                  2370
#define IDC_REMEMBERCANCELLED           2370
#define IDC_QUEUELIST                   2371
#define IDC_SERVERCHANNELLIST           2372
#define IDC_LISTCTRLFILENAMES           2373
#define IDC_S_TITLE                     2374
#define IDC_IRC_MISC_FRM                2375
#define IDC_UDPPORTLABEL                2376
#define IDC_LANG_FRM                    2379
#define IDC_FD_X0                       2381
#define IDC_FD_X1                       2382
#define IDC_FD_X5                       2383
#define IDC_FD_X6                       2384
#define IDC_FD_X7                       2385
#define IDC_FD_X8                       2386
#define IDC_FD_X9                       2387
#define IDC_STATIC30                    2388
#define IDC_FD_X10                      2388
#define IDC_FD_X11                      2389
#define IDC_STATIC31                    2390
#define IDC_STATIC32                    2392
#define IDC_FD_X12                      2393
#define IDC_STATIC_SOFTWARE             2394
#define IDC_FD_X13                      2395
#define IDC_STATIC34                    2396
#define IDC_FD_X14                      2397
#define IDC_STATIC35                    2398
#define IDC_FD_X15                      2400
#define IDC_STATIC38                    2402
#define IDC_FD_LASTCHANGE               2403
#define IDC_STATIC40                    2404
#define IDC_FD_X16                      2405
#define IDC_STATIC41                    2406
#define IDC_STATIC42                    2407
#define IDC_STATIC43                    2408
#define IDC_STATIC44                    2409
#define IDC_STATIC45                    2410
#define IDC_STATIC46                    2411
#define IDC_STATIC47                    2412
#define IDC_STATIC50                    2413
#define IDC_STATIC51                    2414
#define IDC_STATIC52                    2415
#define IDC_STATIC53                    2416
#define IDC_TASKBARNOTIFIER             2418
#define IDC_STATIC48                    2419
#define IDC_EMAILNOT_GROUP              2419
#define IDC_DDOWN_FRM                   2427
#define IDC_MSTATIC7                    2429
#define IDC_FRIENDSICON                 2432
#define IDC_CHATSEND                    2433
#define IDC_FIREWALLCHECKBUTTON         2436
#define IDC_ED2KFIX                     2437
#define IDC_MESSAGEICON                 2439
#define IDC_KADCONNECT                  2440
#define IDC_LOGRESET                    2441
#define IDC_TAB1                        2442
#define IDC_TOTAL_LBL                   2443
#define IDC_WEBSVEDIT                   2444
#define IDC_SERVMSG                     2446
#define IDC_ONLINESIG                   2447
#define IDC_SEARCHLST_ICO               2448
#define IDC_MINIMULE                    2448
#define IDC_SERVLST_ICO                 2449
#define IDC_PREVENTSTANDBY              2449
#define IDC_DOWNLOAD_ICO                2452
#define IDC_METH                        2456
#define IDC_UPLOAD_ICO                  2457
#define IDC_BN_IRCCONNECT               2459
#define IDC_TBN_OPTIONS                 2461
#define IDC_FULL_FILE_INFO              2462
#define IDC_SLIDERINFO                  2463
#define IDC_SLIDERINFO2                 2464
#define IDC_SLIDER2                     2465
#define IDC_SLIDER3                     2466
#define IDC_COLORSELECTOR               2467
#define IDC_FILES_ICO                   2473
#define IDC_NICK_FRM                    2474
#define IDC_TOOLTIPDELAY_LBL            2475
#define IDC_CAPACITIES_FRM              2476
#define IDC_LIMITS_FRM                  2477
#define IDC_DCAP_LBL                    2478
#define IDC_UCAP_LBL                    2479
#define IDC_DLIMIT_LBL                  2480
#define IDC_ULIMIT_LBL                  2481
#define IDC_CLIENTPORT_FRM              2482
#define IDC_MAXCONN_FRM                 2483
#define IDC_MAXSRC_FRM                  2484
#define IDC_MAXSRCHARD_LBL              2485
#define IDC_MISC_FRM                    2488
#define IDC_RETRIES_LBL                 2490
#define IDC_INCOMING_FRM                2491
#define IDC_TEMP_FRM                    2492
#define IDC_SHARED_FRM                  2493
#define IDC_SEEMYSHARE_FRM              2495
#define IDC_MESSAGES_LBL                2496
#define IDD_PPG_NOTIFY                  2498
#define IDC_SLIDERINFO3                 2499
#define IDC_EDIT_TBN_WAVFILE            2500
#define IDD_PPG_IRC                     2501
#define IDC_SMTPSERVER                  2501
#define IDC_GRAPHS                      2502
#define IDC_EDIT_SENDER                 2502
#define IDC_CB_TBN_ONLOG                2503
#define IDD_WIZARD                      2504
#define IDC_EDIT_RECEIVER               2504
#define IDC_STREE                       2505
#define IDC_CB_TBN_POP_ALWAYS           2506
#define IDD_PPG_TWEAKS                  2507
#define IDC_KBS1                        2508
#define IDD_ADDFRIEND                   2509
#define IDC_KBS2                        2510
#define IDC_BTN_BROWSE_WAV              2511
#define IDC_KBS3                        2512
#define IDC_KBS4                        2513
#define IDD_PPG_DEBUG                   2514
#define IDC_CB_TBN_ONDOWNLOAD           2515
#define IDC_IRC_SERVER_FRM              2516
#define IDC_CB_TBN_ONCHAT               2517
#define IDC_IRC_NICK_FRM                2518
#define IDC_IRC_FILTER_FRM              2520
#define IDC_IRC_NAME_TEXT               2521
#define IDC_CB_TBN_IMPORTATNT           2522
#define IDC_IRC_MINUSER_TEXT            2523
#define IDC_CB_ENABLENOTIFICATIONS      2523
#define IDC_IRC_PERFORM_FRM             2524
#define IDC_TAB2                        2526
#define IDC_FILENAME                    2528
#define IDC_FD_SN                       2530
#define IDC_PREFCOLORS                  2531
#define IDC_WIZ_TRUEUPLOAD_BOX          2535
#define IDC_UDPPORT                     2536
#define IDC_USERNAME                    2537
#define IDC_CMT_TEXT                    2538
#define IDC_DEBUG_LOG                   2541
#define IDC_TITLE                       2542
#define IDC_FILTERLEVEL                 2543
#define IDC_TEXT                        2544
#define IDC_WSPORT                      2545
#define IDC_WSTIMEOUT                   2546
#define IDC_BOOTSTRAPIPPORT                 2547
#define IDC_WIZARD                      2548
#define IDC_BOOTSTRAPURL                2548
#define IDC_USERHASH                    2549
#define IDC_INCOMING                    2550
#define IDC_AFKADID                     2550
#define IDC_WSPASS                      2551
#define IDC_IP                          2553
#define IDC_COMMENT                     2554
#define IDC_WSPASSLOW                   2556
#define IDC_AUTOCATEXT                  2558
#define IDC_MMPORT_FIELD                2559
#define IDC_REGEXP                      2559
#define IDC_WIZ_TRUEUPLOAD_TEXT         2564
#define IDC_WIZ_OS_FRAME                2566
#define IDC_WIZ_CONCURENTDOWN_FRAME     2567
#define IDC_WIZ_LOWDOWN_RADIO           2568
#define IDC_WIZ_MEDIUMDOWN_RADIO        2569
#define IDC_WIZ_HIGHDOWN_RADIO          2570
#define IDC_WIZ_TRUEDOWNLOAD_TEXT       2573
#define IDC_WIZ_HOTBUTTON_FRAME         2574
#define IDC_FD_XI3                      2575
#define IDC_FD_XI4                      2576
#define IDC_PROVIDERS                   2578
#define IDC_KBITS                       2579
#define IDC_KBYTES                      2580
#define IDC_FILESIZE                    2581
#define IDC_MAXCONLABEL                 2584
#define IDC_WARNING                     2586
#define IDC_INFO1                       2588
#define IDC_INFO2                       2589
#define IDC_CMT_LQUEST                  2592
#define IDC_CMT_LAIDE                   2593
#define IDC_RATEQUEST                   2595
#define IDC_LST                         2596
#define IDC_RATEHELP                    2597
#define IDC_RATELIST                    2598
#define IDC_TAB3                        2599
#define IDC_3DDEPTH                     2600
#define IDC_3DDEP                       2601
#define IDC_MANUALSERVERHIGHPRIO        2602
#define IDC_DAYS                        2603
#define IDC_ROUND                       2605
#define IDC_STARTUP                     2606
#define IDC_STATICVIDEOPLAYER           2607
#define IDC_FILEBUFFERSIZE              2609
#define IDC_FILEBUFFERSIZE_STATIC       2610
#define IDC_QUEUESIZE_STATIC            2611
#define IDC_QUEUESIZE                   2612
#define IDC_CHECKDAYS                   2613
#define IDC_PREFINI_STATIC              2613
#define IDC_MSG                         2614
#define IDC_FILTERLABEL                 2615
#define IDC_DAP                         2616
#define IDC_FNCLEANUP                   2617
#define IDC_DLTAB                       2618
#define IDC_STATIC_INCOMING             2619
#define IDC_STATIC_TITLE                2620
#define IDC_STATIC_COMMENT              2621
#define IDC_STATIC_DLTOof               2622
#define IDC_STATIC_AUTOCAT              2623
#define IDC_STATIC_REGEXP               2624
#define IDC_FILTERSERVERBYIPFILTER      2626
#define IDC_STATIC_FILTERLEVEL          2627
#define IDC_STATIC_IPFILTER             2628
#define IDC_STATIC_COMMENTS             2629
#define IDC_FILTERSERVERBYIPFILTER2     2629
#define IDC_DONTFILTERPRIVATEIPS        2629
#define IDC_CLIENTLIST                  2630
#define IDC_STATIC_UPDATEFROM           2630
#define IDC_STATIC_FILTERLEVEL2         2631
#define IDC_EDITFILTER                  2632
#define IDC_CATCOLOR                    2633
#define IDC_FILTERCOMMENTSLABEL         2634
#define IDC_WATCHCB                     2635
#define IDC_STATIC_COLOR                2636
#define IDC_PF_TIMECALC                 2636
#define IDC_CATTAB2                     2637
#define IDC_STATIC_CPUMEM               2639
#define IDC_IBLABEL                     2642
#define IDC_WSPORT_LBL                  2643
#define IDC_MMPORT_LBL                  2644
#define IDC_WSPASS_LBL                  2645
#define IDD_PPG_WEBSRV                  2646
#define IDC_WSTIMEOUTLABEL              2646
#define IDC_WSPASS_LBL2                 2647
#define IDC_MMPASSWORD                  2648
#define IDC_STATIC_LOWUSER              2649
#define IDC_STATIC_ADMIN                2650
#define IDC_STATIC_GENERAL              2651
#define IDC_DATETIMEPICKER1             2652
#define IDC_MINS                        2652
#define IDC_STATIC_S_TITLE              2654
#define IDC_STATIC_S_TIME               2655
#define IDC_STATIC_S_ACTION             2656
#define IDC_DATETIMEPICKER2             2657
#define IDC_TIMESEL                     2658
#define IDC_STATIC_DETAILS              2659
#define IDC_NEW                         2660
#define IDC_MSGONLYSEC                  2661
#define IDC_RECONN                      2662
#define IDC_SNAME                       2663
#define IDC_UAP                         2665
#define IDC_SMARTIDCHECK                2666
#define IDC_UPDATEQUEUE                 2667
#define IDC_VIDEOBACKUP                 2668
#define IDC_REPAINT                     2669
#define IDC_WSENABLED                   2671
#define IDC_ENABLE                      2672
#define IDC_WSUPNP                      2672
#define IDC_WS_GZIP                     2673
#define IDC_MSGONLYFRIENDS              2674
#define IDC_WS_ALLOWHILEVFUNC           2674
#define IDC_SELTEMPDIR                  2675
#define IDC_FD_X2                       2676
#define IDC_SELTEMPDIRADD               2676
#define IDC_FD_X3                       2677
#define IDC_FD_X4                       2678
#define IDC_SCHEDACTION                 2679
#define IDC_FD_XAICH                    2679
#define IDC_SCHEDLIST                   2680
#define IDC_EDIT2                       2681
#define IDC_TMPLPATH                    2682
#define IDC_TEMPLATE                    2683
#define IDD_PPG_PROXY                   2684
#define IDC_ENABLEPROXY                 2685
#define IDC_ENABLEAUTH                  2686
#define IDC_PROXYTYPE                   2687
#define IDC_PROXYNAME                   2688
#define IDC_PROXYPORT                   2689
#define IDC_USERNAME_A                  2690
#define IDC_PASSWORD                    2691
#define IDC_PROXYTYPE_LBL               2692
#define IDC_PROXYNAME_LBL               2693
#define IDC_PROXYPORT_LBL               2694
#define IDC_USERNAME_LBL                2695
#define IDC_PASSWORD_LBL                2696
#define IDC_AUTH_LBL                    2697
#define IDC_LISTVIEW_SEARCH_COLUMN      2700
#define IDC_LISTVIEW_SEARCH_TEXT        2702
#define IDC_AUTH_LBL2                   2703
#define IDC_WIZ1_TITLE                  2704
#define IDC_WIZ1_ACTIONS                2705
#define IDC_WIZ1_BTN_HINT               2706
#define IDD_PPG_DISPLAY                 2707
#define IDD_CAT                         2708
#define IDR_TASKBAR                     2709
#define IDD_PPG_SECURITY                2710
#define IDC_STATIC_PRIO                 2712
#define IDC_PRIOCOMBO                   2713
#define IDR_WIZ1_WATERMARK              2714
#define IDR_WIZ1_HEADER                 2715
#define IDC_STARTNEXTFILECAT            2716
#define IDD_WIZ1_WELCOME                2717
#define IDD_WIZ1_GENERAL                2718
#define IDC_STARTNEXTFILECAT2           2718
#define IDD_WIZ1_PORTS                  2719
#define IDD_WIZ1_ULDL_PRIO              2720
#define IDD_WIZ1_UPLOAD                 2721
#define IDD_WIZ1_SERVER                 2722
#define IDD_WIZ1_END                    2723
#define IDD_WIZ1_EXTRES                 2724
#define IDD_KADEMLIAWND                 2726
#define IDC_LAST_SEEN_LABEL             2727
#define IDC_ONND                        2728
#define IDC_FNC                         2729
#define IDC_CRATIO                      2730
#define IDC_STATIC_CGRAPHSCALE          2732
#define IDC_STATIC_CGRAPHRATIO          2733
#define IDC_CGRAPHSCALE                 2734
#define IDC_BNMENU                      2735
#define IDC_STATIC_LASTRESET            2736
#define IDC_LISTVIEW_SEARCH_TEXT_LBL    2740
#define IDC_LISTVIEW_SEARCH_COLUMN_LBL  2741
#define IDC_STATIC133x                  2743
#define IDC_CDIDENT                     2744
#define IDC_UNCADD                      2745
#define IDC_UNCREM                      2746
#define IDC_SEC_MISC                    2747
#define IDC_SEC_OBFUSCATIONBOX          2748
#define IDC_MMPASSWORDFIELD             2749
#define IDC_HYPERTEXT_FONT_HINT         2750
#define IDC_GUIDELINK                   2751
#define IDC_RESETLABEL                  2752
#define IDC_KADSEARCHLAB                2753
#define IDC_KADCONTACTLAB               2754
#define IDC_PV_IMAGE                    2761
#define IDC_CONNECTION_NETWORK          2762
#define IDC_WIZARD_NETWORK              2763
#define IDC_WIZARD_ED2K                 2764
#define IDC_CLEANFILENAME               2765
#define IDC_BSSTATIC                    2766
#define IDD_FILEDETAILS_INFO            2767
#define IDC_BUTTONSTRIP                 2769
#define IDD_FILEDETAILS_NAME            2770
#define IDC_CHECKNOENDTIME              2771
#define IDC_TOTAL_TAGS                  2772
#define IDC_MAXUP_SLIDER                2774
#define IDC_MAXDOWN_SLIDER              2775
#define IDD_PREVIEWDIALOG               2776
#define IDC_PREVIEW_INFO                2777
#define IDC_HIDECONVDLG                 2778
#define IDC_HASHSET                     2779
#define IDC_JOBLIST                     2780
#define IDC_RECOVERED                   2781
#define IDC_CONV_PB_LABEL               2782
#define IDC_CONV_PROZENT                2783
#define IDC_CURJOB                      2784
#define IDD_CONVERTPARTFILES            2785
#define IDC_CORRUPTED                   2786
#define IDD_IPFILTER                    2786
#define IDC_COMPRESSION                 2787
#define IDD_ED2KLINK                    2787
#define IDC_TIMELEFTTEXT                2789
#define IDC_TRANSFER_RATE_LABEL         2790
#define IDC_RADIP                       2791
#define IDC_RADCLIENTS                  2792
#define IDC_HSAV                        2793
#define IDC_RADNODESURL                 2793
#define IDC_FD_CORR                     2794
#define IDC_FD_RECOV                    2795
#define IDC_FD_COMPR                    2796
#define IDC_UPDATEURL                   2797
#define IDC_REMAINING                   2798
#define IDC_DD                          2799
#define IDC_REMAINING_TEXT              2800
#define IDC_TRAY_EXIT                   2802
#define IDC_DOWNKB                      2803
#define IDC_UPKB                        2804
#define IDC_DOWNLBL                     2805
#define IDC_UPLBL                       2806
#define IDC_PREFERENCES                 2807
#define IDC_TOTAL_IPFILTER_LABEL        2808
#define IDC_TOTAL_IPFILTER              2809
#define IDC_IPFILTER                    2810
#define IDC_SAVE                        2811
#define IDC_TOTAL_IPS_LABEL             2812
#define IDC_TOTAL_IPS                   2813
#define IDC_APPEND                      2815
#define IDC_FORMAT                      2816
#define IDC_STATICIPLABEL               2818
#define IDC_MISC_IRC                    2819
#define IDC_DL_ACTIVE_TIME_LBL          2820
#define IDC_SEARCH_OPTS                 2833
#define IDC_DISABLEHIST                 2834
#define IDC_OPEN_PARAMS_WND             2835
#define IDC_PREVIEW                     2837
#define IDC_KADICO1                     2838
#define IDC_KADICO2                     2839
#define IDC_CATLABEL                    2840
#define IDC_CATS                        2841
#define IDC_STATICFI                    2842
#define IDC_RESET                       2843
#define IDC_OPENPORTS                   2844
#define IDC_SMILEY                      2844
#define IDC_TCP                         2845
#define IDC_UDP                         2846
#define IDC_TCP_LABEL                   2847
#define IDC_UDP_LABEL                   2848
#define IDC_TESTINFO                    2849
#define IDC_PORTINFO                    2850
#define IDC_SPLITTER_IRC_CHANNEL        2851
#define IDC_TESTFRAME                   2852
#define IDC_STARTTEST                   2853
#define IDC_KAD_HISTOGRAM               2854
#define IDC_KAD_LOOKUPGRAPH             2855
#define IDC_NETWORK_INFO                2856
#define IDC_NETWORK_INFO_LABEL          2857
#define IDC_SPLITTER_IRC                2858
#define IDC_SPLITTER_STAT               2859
#define IDC_SPLITTER_STAT_HR            2860
#define IDC_SPLITTER_STAT_HL            2861
#define IDC_FRIENDS_USERHASH            2862
#define IDC_FRIENDS_NAME                2863
#define IDC_FRIENDS_CLIENT              2864
#define IDC_FRIENDS_UPLOADED            2865
#define IDC_FRIENDS_DOWNLOADED          2866
#define IDC_FRIENDS_IDENT               2867
#define IDC_FRIENDS_MSG                 2868
#define IDC_FRIENDS_NAME_EDIT           2869
#define IDC_FRIENDS_USERHASH_EDIT       2870
#define IDC_FRIENDS_CLIENTE_EDIT        2871
#define IDC_FRIENDS_IDENTIFICACION_EDIT 2872
#define IDC_FRIENDS_SUBIDO_EDIT         2873
#define IDC_FRIENDS_DESCARGADO_EDIT     2874
#define IDC_SPLITTER_FRIEND             2875
#define IDC_CLIENTDETAIL_KAD            2876
#define IDC_LD_LINKEDI                  2877
#define IDC_CLIENTDETAIL_KADCON         2878
#define IDC_AUTOSTART                   2880
#define IDC_STARTWIN                    2882
#define IDC_EDIT3                       2887
#define IDC_BUTTON1                     2899
#define IDC_LD_LINKGROUP                2900
#define IDC_LD_BASICGROUP               2901
#define IDC_LD_ADVANCEDGROUP            2902
#define IDC_LD_CLIPBOARDBUT             2903
#define IDC_LD_SOURCECHE                2904
#define IDC_LD_HTMLCHE                  2905
#define IDC_LD_HASHSETCHE               2906
#define IDC_LD_EMULEHASHCHE             2907
#define IDC_LD_HOSTNAMECHE              2908
#define IDC_UIP                         2910
#define IDC_REGEXPR                     2912
#define IDC_SEARCHKAD                   2913
#define IDC_CB_TBN_NOSOUND              2914
#define IDC_CB_TBN_USESOUND             2915
#define IDC_CB_TBN_USESPEECH            2916
#define IDC_TEST_NOTIFICATION           2917
#define IDC_DOWNLOADCLIENTS             2918
#define IDC_TXT_SMTPSERVER              2919
#define IDC_TXT_RECEIVER                2920
#define IDC_TXT_SENDER                  2921
#define IDC_USERCOMMENTS                2922
#define IDD_COLLECTIONCREATEDIALOG      2923
#define IDD_COLLECTIONVIEWDIALOG        2924
#define IDC_COLLECTIONLISTCTRL          2924
#define IDC_COLLECTIONAVAILLIST         2925
#define IDC_COLLECTIONVIEWCATEGORYCHECK 2925
#define IDC_COLLECTIONADD               2926
#define IDC_SHAREDDIRSTREE              2926
#define IDC_COLLECTIONREMOVE            2927
#define IDC_COLLECTIONVEWLIST           2928
#define IDC_COLLECTIONLISTICON          2928
#define IDC_COLLECTIONSOURCELISTICON    2929
#define IDC_COLLECTIONVIEWLISTLABEL     2930
#define IDC_COLLECTIONLISTLABEL         2931
#define IDC_COLLECTIONVIEWLISTICON      2931
#define IDC_COLLECTIONNAMEEDIT          2932
#define IDC_VIEWCOLLECTIONDL            2933
#define IDC_COLLECTIONVIEWSHAREBUTTON   2935
#define IDC_COLLECTIONVIEWAUTHORLABEL   2935
#define IDC_COLLECTIONVIEWAUTHOR        2936
#define IDC_COLLECTIONVIEWAUTHORKEYLABEL 2937
#define IDC_COLLECTIONVIEWAUTHORKEY     2939
#define IDC_COLLECTIONCREATESIGNCHECK   2940
#define IDC_COLLECTIONCREATEFORMAT      2941
#define IDC_CCOLL_STATIC_NAME           2942
#define IDC_SPLITTER_SERVER             2943
#define IDC_SPLITTER_SHAREDFILES        2944
#define IDC_VCOLL_DETAILS               2945
#define IDC_VCOLL_OPTIONS               2946
#define IDC_VCOLL_CLOSE                 2947
#define IDC_CCOLL_SAVE                  2948
#define IDC_CCOLL_CANCEL                2949
#define IDC_CCOLL_BASICOPTIONS          2950
#define IDC_CCOLL_ADVANCEDOPTIONS       2951
#define IDC_ALANGUAGE                   2952
#define IDC_COLOUR                      2953
#define IDC_UNDERLINE                   2954
#define IDC_BOLD                        2955
#define IDC_VIDEOPLAYER_ARGS_LBL        2958
#define IDC_VIDEOPLAYER_CMD_LBL         2959
#define IDC_FILELIST                    2965
#define IDC_READARCH                    2966
#define IDC_INFO_TYPE                   2967
#define IDC_INFO_STATUS                 2968
#define IDC_INFO_FILECOUNT              2969
#define IDC_INFO_ATTR                   2970
#define IDC_ARCP_TYPE                   2971
#define IDC_ARCP_STATUS                 2972
#define IDC_ARCP_ATTRIBS                2973
#define IDC_APV_FILEINFO                2974
#define IDC_RESTOREARCH                 2975
#define IDC_STATIC_OBF_LABEL            2976
#define IDC_OBFUSCATION_STAT            2977
#define IDC_STATIC_LANGUAGE             2978
#define IDC_AP_EXPLAIN                  2979
#define IDD_ARCHPREV                    2980
#define IDD_PPG_MESSAGES                2981
#define IDC_ARCHPROGRESS                2982
#define IDC_FILL_GRAPHS                 2983
#define IDC_GENERAL                     2984
#define IDC_LBL_UPDATE_SERVERS          2985
#define IDC_LBL_MISC                    2986
#define IDC_UPNPSTART                   2987
#define IDC_UPNPPROGRESS                2988
#define IDC_UPNPSTATUS                  2989
#define IDC_PREF_UPNPONSTART            2990
#define IDC_NODESDATLABEL               2991
#define IDC_AFKADIDLABEL                2993
#define IDC_SHAREDFILES_FILTER          2994
#define IDC_EDITCOMMENTFILTER           2995
#define IDC_WIZZARDOBFUSCATION          2996
#define IDC_TOOLTIPDELAY_SPIN           2997
#define IDC_CHECK_FILE_OPEN             2998
#define IDC_DTOOLBAR                    2999
#define IDC_ADDSOURCE_STATUS            3048
#define IDC_STATISTICS_GB               3000
#define IDC_STATISTICS_GB_SESSION       3000
#define IDC_SF_HIDESHOWDETAILS          3002
#define IDC_STATISTICS_GB_TOTAL         3003
#define IDC_FS_POPULARITY_LBL           3004
#define IDC_FS_POPULARITY_VAL           3005
#define IDC_FS_ONQUEUE_LBL              3006
#define IDC_FS_ONQUEUE_VAL              3007
#define IDC_FS_UPLOADING_LBL            3008
#define IDC_FS_UPLOADING_VAL            3009
#define IDC_FS_POPULARITY2_LBL          3010
#define IDC_FS_POPULARITY2_VAL          3011
#define IDC_OPENPREFINI                 3012
#define IDC_WEB_HTTPS                   3013
#define IDC_WEB_CERT                    3014
#define IDC_CERTPATH                    3015
#define IDC_CERTBROWSE                  3016
#define IDC_WEB_KEY                     3017
#define IDC_KEYPATH                     3018
#define IDC_KEYBROWSE                   3019
#define IDC_ITALIC                      3020
#define IDC_WEB_GENERATE                3021
#define IDC_DONOTASKAGAIN               3022
#define IDD_EXITBOX                     3023
#define IDC_MAIN_EXIT                   3024
#define IDC_SMTPCONN_GROUP              3025
#define IDC_SMTPSEC_LBL                 3026
#define IDC_SMTPSEC                     3027
#define IDC_SMTPSERVER_LBL              3028
#define IDC_SMTPPORT_LBL                3029
#define IDC_SMTPPORT                    3030
#define IDC_SMTPAUTH_GROUP              3031
#define IDC_SMTPAUTH                    3032
#define IDC_SMTPUSER_LBL                3033
#define IDC_SMTPUSER                    3034
#define IDC_SMTPPASS_LBL                3035
#define IDC_SMTPPASS                    3036
#define IDC_SF_FICON                    3037
#define IDC_BUTTON2                     3042
#define IDC_FILETYPE                    3044
#define IDA_ENTER                       32771
#define IDC_DD2                         32772
#define IDI_FLAG_NOFLAG                 40000
#define IDI_FLAG_A1                     40001
#define IDI_FLAG_A2                     40002
#define IDI_FLAG_AD                     40003
#define IDI_FLAG_AE                     40004
#define IDI_FLAG_AF                     40005
#define IDI_FLAG_AG                     40006
#define IDI_FLAG_AI                     40007
#define IDI_FLAG_AL                     40008
#define IDI_FLAG_AM                     40009
#define IDI_FLAG_AO                     40010
#define IDI_FLAG_AQ                     40011
#define IDI_FLAG_AR                     40012
#define IDI_FLAG_AS                     40013
#define IDI_FLAG_AT                     40014
#define IDI_FLAG_AU                     40015
#define IDI_FLAG_AW                     40016
#define IDI_FLAG_AX                     40017
#define IDI_FLAG_AZ                     40018
#define IDI_FLAG_BA                     40019
#define IDI_FLAG_BB                     40020
#define IDI_FLAG_BD                     40021
#define IDI_FLAG_BE                     40022
#define IDI_FLAG_BF                     40023
#define IDI_FLAG_BG                     40024
#define IDI_FLAG_BH                     40025
#define IDI_FLAG_BI                     40026
#define IDI_FLAG_BJ                     40027
#define IDI_FLAG_BL                     40028
#define IDI_FLAG_BM                     40029
#define IDI_FLAG_BN                     40030
#define IDI_FLAG_BO                     40031
#define IDI_FLAG_BQ                     40032
#define IDI_FLAG_BR                     40033
#define IDI_FLAG_BS                     40034
#define IDI_FLAG_BT                     40035
#define IDI_FLAG_BV                     40036
#define IDI_FLAG_BW                     40037
#define IDI_FLAG_BY                     40038
#define IDI_FLAG_BZ                     40039
#define IDI_FLAG_CA                     40040
#define IDI_FLAG_CC                     40041
#define IDI_FLAG_CD                     40042
#define IDI_FLAG_CF                     40043
#define IDI_FLAG_CG                     40044
#define IDI_FLAG_CH                     40045
#define IDI_FLAG_CI                     40046
#define IDI_FLAG_CK                     40047
#define IDI_FLAG_CL                     40048
#define IDI_FLAG_CM                     40049
#define IDI_FLAG_CN                     40050
#define IDI_FLAG_CO                     40051
#define IDI_FLAG_CR                     40052
#define IDI_FLAG_CU                     40053
#define IDI_FLAG_CV                     40054
#define IDI_FLAG_CW                     40055
#define IDI_FLAG_CX                     40056
#define IDI_FLAG_CY                     40057
#define IDI_FLAG_CZ                     40058
#define IDI_FLAG_DE                     40059
#define IDI_FLAG_DJ                     40060
#define IDI_FLAG_DK                     40061
#define IDI_FLAG_DM                     40062
#define IDI_FLAG_DO                     40063
#define IDI_FLAG_DZ                     40064
#define IDI_FLAG_EC                     40065
#define IDI_FLAG_EE                     40066
#define IDI_FLAG_EG                     40067
#define IDI_FLAG_EH                     40068
#define IDI_FLAG_ER                     40069
#define IDI_FLAG_ES                     40070
#define IDI_FLAG_ET                     40071
#define IDI_FLAG_EU                     40072
#define IDI_FLAG_FI                     40073
#define IDI_FLAG_FJ                     40074
#define IDI_FLAG_FK                     40075
#define IDI_FLAG_FM                     40076
#define IDI_FLAG_FO                     40077
#define IDI_FLAG_FR                     40078
#define IDI_FLAG_GA                     40079
#define IDI_FLAG_GB                     40080
#define IDI_FLAG_GD                     40081
#define IDI_FLAG_GE                     40082
#define IDI_FLAG_GF                     40083
#define IDI_FLAG_GG                     40084
#define IDI_FLAG_GH                     40085
#define IDI_FLAG_GI                     40086
#define IDI_FLAG_GL                     40087
#define IDI_FLAG_GM                     40088
#define IDI_FLAG_GN                     40089
#define IDI_FLAG_GP                     40090
#define IDI_FLAG_GQ                     40091
#define IDI_FLAG_GR                     40092
#define IDI_FLAG_GS                     40093
#define IDI_FLAG_GT                     40094
#define IDI_FLAG_GU                     40095
#define IDI_FLAG_GW                     40096
#define IDI_FLAG_GY                     40097
#define IDI_FLAG_HK                     40098
#define IDI_FLAG_HM                     40099
#define IDI_FLAG_HN                     40100
#define IDI_FLAG_HR                     40101
#define IDI_FLAG_HT                     40102
#define IDI_FLAG_HU                     40103
#define IDI_FLAG_ID                     40104
#define IDI_FLAG_IE                     40105
#define IDI_FLAG_IL                     40106
#define IDI_FLAG_IM                     40107
#define IDI_FLAG_IN                     40108
#define IDI_FLAG_IO                     40109
#define IDI_FLAG_IQ                     40110
#define IDI_FLAG_IR                     40111
#define IDI_FLAG_IS                     40112
#define IDI_FLAG_IT                     40113
#define IDI_FLAG_JE                     40114
#define IDI_FLAG_JM                     40115
#define IDI_FLAG_JO                     40116
#define IDI_FLAG_JP                     40117
#define IDI_FLAG_KE                     40118
#define IDI_FLAG_KG                     40119
#define IDI_FLAG_KH                     40120
#define IDI_FLAG_KI                     40121
#define IDI_FLAG_KM                     40122
#define IDI_FLAG_KN                     40123
#define IDI_FLAG_KP                     40124
#define IDI_FLAG_KR                     40125
#define IDI_FLAG_KW                     40126
#define IDI_FLAG_KY                     40127
#define IDI_FLAG_KZ                     40128
#define IDI_FLAG_LA                     40129
#define IDI_FLAG_LB                     40130
#define IDI_FLAG_LC                     40131
#define IDI_FLAG_LI                     40132
#define IDI_FLAG_LK                     40133
#define IDI_FLAG_LR                     40134
#define IDI_FLAG_LS                     40135
#define IDI_FLAG_LT                     40136
#define IDI_FLAG_LU                     40137
#define IDI_FLAG_LV                     40138
#define IDI_FLAG_LY                     40139
#define IDI_FLAG_MA                     40140
#define IDI_FLAG_MC                     40141
#define IDI_FLAG_MD                     40142
#define IDI_FLAG_ME                     40143
#define IDI_FLAG_MF                     40144
#define IDI_FLAG_MG                     40145
#define IDI_FLAG_MH                     40146
#define IDI_FLAG_MK                     40147
#define IDI_FLAG_ML                     40148
#define IDI_FLAG_MM                     40149
#define IDI_FLAG_MN                     40150
#define IDI_FLAG_MO                     40151
#define IDI_FLAG_MP                     40152
#define IDI_FLAG_MQ                     40153
#define IDI_FLAG_MR                     40154
#define IDI_FLAG_MS                     40155
#define IDI_FLAG_MT                     40156
#define IDI_FLAG_MU                     40157
#define IDI_FLAG_MV                     40158
#define IDI_FLAG_MW                     40159
#define IDI_FLAG_MX                     40160
#define IDI_FLAG_MY                     40161
#define IDI_FLAG_MZ                     40162
#define IDI_FLAG_NA                     40163
#define IDI_FLAG_NC                     40164
#define IDI_FLAG_NE                     40165
#define IDI_FLAG_NF                     40166
#define IDI_FLAG_NG                     40167
#define IDI_FLAG_NI                     40168
#define IDI_FLAG_NL                     40169
#define IDI_FLAG_NO                     40170
#define IDI_FLAG_NP                     40171
#define IDI_FLAG_NR                     40172
#define IDI_FLAG_NU                     40173
#define IDI_FLAG_NZ                     40174
#define IDI_FLAG_OM                     40175
#define IDI_FLAG_PA                     40176
#define IDI_FLAG_PE                     40177
#define IDI_FLAG_PF                     40178
#define IDI_FLAG_PG                     40179
#define IDI_FLAG_PH                     40180
#define IDI_FLAG_PK                     40181
#define IDI_FLAG_PL                     40182
#define IDI_FLAG_PM                     40183
#define IDI_FLAG_PN                     40184
#define IDI_FLAG_PR                     40185
#define IDI_FLAG_PS                     40186
#define IDI_FLAG_PT                     40187
#define IDI_FLAG_PW                     40188
#define IDI_FLAG_PY                     40189
#define IDI_FLAG_QA                     40190
#define IDI_FLAG_RE                     40191
#define IDI_FLAG_RO                     40192
#define IDI_FLAG_RS                     40193
#define IDI_FLAG_RU                     40194
#define IDI_FLAG_RW                     40195
#define IDI_FLAG_SA                     40196
#define IDI_FLAG_SB                     40197
#define IDI_FLAG_SC                     40198
#define IDI_FLAG_SD                     40199
#define IDI_FLAG_SE                     40200
#define IDI_FLAG_SG                     40201
#define IDI_FLAG_SH                     40202
#define IDI_FLAG_SI                     40203
#define IDI_FLAG_SJ                     40204
#define IDI_FLAG_SK                     40205
#define IDI_FLAG_SL                     40206
#define IDI_FLAG_SM                     40207
#define IDI_FLAG_SN                     40208
#define IDI_FLAG_SO                     40209
#define IDI_FLAG_SR                     40210
#define IDI_FLAG_SS                     40211
#define IDI_FLAG_ST                     40212
#define IDI_FLAG_SV                     40213
#define IDI_FLAG_SX                     40214
#define IDI_FLAG_SY                     40215
#define IDI_FLAG_SZ                     40216
#define IDI_FLAG_TC                     40217
#define IDI_FLAG_TD                     40218
#define IDI_FLAG_TF                     40219
#define IDI_FLAG_TG                     40220
#define IDI_FLAG_TH                     40221
#define IDI_FLAG_TJ                     40222
#define IDI_FLAG_TK                     40223
#define IDI_FLAG_TL                     40224
#define IDI_FLAG_TM                     40225
#define IDI_FLAG_TN                     40226
#define IDI_FLAG_TO                     40227
#define IDI_FLAG_TR                     40228
#define IDI_FLAG_TT                     40229
#define IDI_FLAG_TV                     40230
#define IDI_FLAG_TW                     40231
#define IDI_FLAG_TZ                     40232
#define IDI_FLAG_UA                     40233
#define IDI_FLAG_UG                     40234
#define IDI_FLAG_UM                     40235
#define IDI_FLAG_US                     40236
#define IDI_FLAG_UY                     40237
#define IDI_FLAG_UZ                     40238
#define IDI_FLAG_VA                     40239
#define IDI_FLAG_VC                     40240
#define IDI_FLAG_VE                     40241
#define IDI_FLAG_VG                     40242
#define IDI_FLAG_VI                     40243
#define IDI_FLAG_VN                     40244
#define IDI_FLAG_VU                     40245
#define IDI_FLAG_WF                     40246
#define IDI_FLAG_WS                     40247
#define IDI_FLAG_XK                     40248
#define IDI_FLAG_YE                     40249
#define IDI_FLAG_YT                     40250
#define IDI_FLAG_ZA                     40251
#define IDI_FLAG_ZM                     40252
#define IDI_FLAG_ZW                     40253
#define IDD_SPEEDGRAPH                  40254
#define IDD_DARKMODE_MSGBOX             40255
#define IDC_DARKMODE_ICON               40256
#define IDC_DARKMODE_TEXT               40257
#define IDR_MOD_BANNER                  40258
#define IDR_MOD_BANNER_LIGHT            40259
#define IDC_CLIENT_IP                   49874
#define IDC_STATIC_CLIENT_IP            49875
#define IDC_CHECK_BADCLIENT             49876
#define IDC_CHECK_FREEEZE               49877
#define IDC_CHECK_ARCHIVED              49878
#define IDC_CHECK_COMPLETE              49879
#define IDC_CHECK_FREEEZE2              49879
#define IDC_CHECK_PREVIEW               49879
#define IDC_CHECK_QUERYABLE             49880
#define IDC_CHECK_VALIDIP               49881
#define IDC_CHECK_HIGHID                49882
#define IDC_FILTER_DOWNLOAD_LIST        49883
#define IDC_FILTER_UPLOAD_LIST          49884
#define IDC_FILTER_QUEUE_LIST           49885
#define IDC_FILTER_CLIENT_LIST          49886
#define IDC_FILTER_DOWNLOAD_CLIENTS     49887
#define IDC_CHECK_NOT_QUERIED           49888
#define IDC_BTN_MENU                    49889
#define IDC_DSCOUNTRY                   49900
#define IDC_STATIC_BAD_CLIENT_TYPE      49901
#define IDC_STATIC_PUNISHMENT           49902
#define IDC_BLACKLIST_ENABLE_CHECKBOX   49951
#define IDC_BLACKLIST_ENABLE_AUTOMATIC_CHECKBOX 49952
#define IDC_SF_FNAME                    49953
#define IDC_BLACKLIST_ENABLE_CHECKBOX2  49954
#define IDC_BLACKLIST_ENABLE_MANUAL_CHECKBOX 49955
#define IDC_BLACKLIST_OPT_FRM           49956
#define IDC_BLACKLIST_DEF_FRM           49957
#define IDC_BLACKLIST_LOG_CHECKBOX      49958
#define IDC_BLACKLIST_AUTOREMOVE_CHECKBOX 49959
#define IDC_LEECHERLOG                  50039
#define IDC_LEECHER                     50040
#define IDC_GEOLOCATION_TXT             50041
#define IDC_STATIC_GEOLOCATION          50042
#define IDC_COUNTRY_FLAG_ICON           50043
#define IDC_PUNISHMENT                  50044
#define IDC_BTL                         50216
#define IDC_BTL_TEXT                    50217
#define IDD_PPG_PROTECTION_PANEL        50218
#define IDC_PROTECTION_PANEL_OPTS       50219
#define IDC_SHIELD_STATIC               50220
#define IDC_SHIELD_RELOAD               50221
#define IDC_MOD_OPTS                    51341
#define IDC_MOD_OPTS_INFO               51342
#define IDC_PROTECTION_PANEL_OPTS_INFO  51343
#define IDD_PPG_MOD                     51344
#define IDC_SHARE_ICO                   51345
#define IDD_PPG_BLACKLIST_PANEL         51347
#define IDC_BLACKLIST_DEFINITIONS_TEXTBOX 51348
#define IDC_BLACKLIST_PANEL_HELP_TEXTBOX 51349
#define IDC_NETWORK_INFO_AUTOREFRESH    51350
#define IDC_NATT_FORCE_PUBLISH          51351

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1693
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         3059
#define _APS_NEXT_SYMED_VALUE           1610
#endif
#endif
