#pragma once

// ALL WM_USER messages are to be declared here *after* 'WM_FIRST_EMULE_USER_MSG'
enum EUserWndMessages
{
	// *) Do *NOT* place any message *before* WM_FIRST_EMULE_USER_MSG !!
	// *) Do *NOT* use any WM_USER messages in the range WM_USER - WM_USER+0x104 !! (AsyncSocketEx)
	UM_FIRST_EMULE_USER_MSG = (WM_USER + 0x110 + 1),

	// Taskbar
	UM_TASKBARNOTIFIERCLICKED, //+2
	UM_TRAY_ICON_NOTIFY_MESSAGE,
	UM_CLOSE_MINIMULE,

	// Web Server
	WEB_GUI_INTERACTION, //+5
	WEB_CLEAR_COMPLETED,
	WEB_FILE_RENAME,
	WEB_ADDDOWNLOADS,
	WEB_CATPRIO,
	WEB_ADDREMOVEFRIEND,

	// VC
	UM_VERSIONCHECK_RESPONSE, //+11

	UM_CLOSETAB,	//+13
	UM_QUERYTAB,
	UM_DBLCLICKTAB,

	UM_CPN_SELCHANGE, //+16
	UM_CPN_DROPDOWN,
	UM_CPN_CLOSEUP,
	UM_CPN_SELENDOK,
	UM_CPN_SELENDCANCEL,

	UM_MEDIA_INFO_RESULT, //+21
	UM_ITEMSTATECHANGED,
	UM_SPN_SIZED,
	UM_TABMOVED,
	UM_TREEOPTSCTRL_NOTIFY,
	UM_DATA_CHANGED,
	UM_OSCOPEPOSITION,
	UM_DELAYED_EVALUATE,
	UM_ARCHIVESCANDONE,

	// UPnP
	UM_UPNP_RESULT, //+30

	UM_SHOWFILESCOUNT,
	UM_METADATAUPDATED,
	UM_EMPTYFAKEFILEFOUND,
	UM_INVALIDEXTENSIONFOUND,
	UM_FINALIZE_DELETE_PENDING_CLIENT,
	UM_APP_SWITCH_DARKMODE,
	UM_AUTO_RELOAD_SHARED_FILES,
	UM_INVALIDATE_CAT_TAB_INFO,
	UM_UPDATE_CAT_TAB_TITLES,
	UM_SHARED_FILES_ADJUST_DETAILS_PANEL,
	UM_UPDATE_QUEUE_COUNT,
	WEB_GET_SEARCH_RESULTS,
	WEB_START_SEARCH,
	WEB_GET_SEARCH_DOWNLOAD_LINKS,
	WEB_GET_TRANSFER_SNAPSHOT,
	WEB_GET_SHARED_FILES_SNAPSHOT,
	WEB_GET_SERVER_LIST_SNAPSHOT,
	WEB_SERVER_COMMAND,
	WEB_GET_HEADER_SNAPSHOT,
	WEB_GET_SHARED_FILE_DOWNLOAD_INFO,
	WEB_GET_COMMENT_LIST,
	WEB_FRIEND_COMMAND,
	UM_WORKER_TOPOLOGY_EVENT,
	UM_WORKER_TOPOLOGY_DRAINED,
	UM_SHARED_FILES_SELECTION_DETAILS,
	UM_STARTUP_LOADING_CANCEL_EXIT,
	UM_BIND_ADDRESS_CHANGED,
	UM_IP_GUARD_PROBE_RESULT,
	UM_TOAST_NOTIFICATION_CLICKED
};
